version: '3'

services:

    nginx-test:
        container_name: nginx-test
        build: 
            context: . 
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
        #     - 'app/node_modules'
        ports:
            - '3001:3000'
        networks:
            - nginx-test-network

    reverseproxy:
        container_name: reverseproxy
        hostname: reverseproxy
        image: nginx
        ports: 
            - 80:80
        volumes:
            - ./nginx:/etc/nginx
        networks:
            - nginx-test-network
        depends_on:
            - nginx-test

networks:
    nginx-test-network:    
